nelmio_cors:
    defaults:
        allow_origin: ['*'] # à restreindre en production !
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: []
        max_age: 3600
        allow_credentials: false
    paths:
        '^/proxy-googleads': ~
